<?xml version="1.0" encoding="UTF-8"?>
 
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
https://maven.apache.org/xsd/maven-4.0.0.xsd">
 
    <modelVersion>4.0.0</modelVersion>
 
    <groupId>com.demo</groupId>
<artifactId>assignment1-harshitha</artifactId>
<version>1.0</version>
<packaging>war</packaging>
 
    <properties>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
 
        <sonar.organization>harshitha-21v</sonar.organization>
<sonar.projectKey>harshitha-21v_CICD-Workflow-1</sonar.projectKey>
<sonar.host.url>https://sonarcloud.io</sonar.host.url>
</properties>
 
    <build>
<finalName>assignment1-harshitha</finalName>
 
        <plugins>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-war-plugin</artifactId>
<version>3.4.0</version>
 
                <configuration>
<failOnMissingWebXml>false</failOnMissingWebXml>
</configuration>
</plugin>
</plugins>
</build>
 
</project>
     

 

      
  
